export { default as Home } from './Home'
export { default as Main } from './Main'
export { default as Test } from './Test'
export { default as Splash } from './Splash'
export { default as Login } from './Login'